services:
  web:
    image: webdevops/php-apache:8.1-alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/app
    networks:
      - pdo-network
    working_dir: /app

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - pdo-network

networks:
  pdo-network:
    driver: bridge